// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// awards_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Iawards_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentawardsSchema property.
        /// </summary>
		awardsSchema CurrentawardsSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechawards_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechawards_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Shareawards_DetailStaticControlCommand command.
        /// </summary>
		ICommand Shareawards_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartawards_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartawards_DetailStaticControlCommand { get; }

	}
}
