// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// blog_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Iblog_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechblog_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechblog_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Shareblog_DetailStaticControlCommand command.
        /// </summary>
		ICommand Shareblog_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartblog_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartblog_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceblog_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceblog_DetailStaticControlCommand { get; }

	}
}
