// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// TheTeam_Album ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ITheTeam_AlbumViewModel
    {		
        /// <summary>
        /// Gets/Sets the TheTeam_AlbumListControlCollection property.
        /// </summary>
		ObservableCollection<TheGuysCollectionSchema> TheTeam_AlbumListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedTheTeam_AlbumListControlCollection property.
        /// </summary>
		TheGuysCollectionSchema SelectedTheTeam_AlbumListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Awards_ListListControlCollection property.
        /// </summary>
		ObservableCollection<awardsSchema> Awards_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Selectedawards_ListListControlCollection property.
        /// </summary>
		awardsSchema Selectedawards_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Videos_VideosListControlCollection property.
        /// </summary>
		ObservableCollection<YouTubeVideo> Videos_VideosListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Selectedvideos_VideosListControlCollection property.
        /// </summary>
		YouTubeVideo Selectedvideos_VideosListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Blog_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<RssSearchResult> Blog_NewsListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Selectedblog_NewsListControlCollection property.
        /// </summary>
		RssSearchResult Selectedblog_NewsListControlCollection { get; set; }

        
        /// <summary>
        /// Gets the Refreshvideos_VideosListControlCollection command.
        /// </summary>
		ICommand Refreshvideos_VideosListControlCollection { get; }

        
        /// <summary>
        /// Gets the Refreshblog_NewsListControlCollection command.
        /// </summary>
		ICommand Refreshblog_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

	}
}
