// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// TheTeam_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ITheTeam_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentTheGuysCollectionSchema property.
        /// </summary>
		TheGuysCollectionSchema CurrentTheGuysCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechTheTeam_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechTheTeam_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareTheTeam_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareTheTeam_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartTheTeam_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartTheTeam_DetailStaticControlCommand { get; }

	}
}
