// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// videos_DetailVideos ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Ivideos_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		YouTubeVideo CurrentYouTubeVideo { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechvideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechvideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharevideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand Sharevideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartvideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartvideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourcevideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourcevideos_DetailVideosStaticControlCommand { get; }

	}
}
