// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of awards_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class awards_DetailViewModel : BindableBase, Iawards_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="awards_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public awards_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private awardsSchema _currentawardsSchema;

        /// <summary>
        /// CurrentawardsSchema property.
        /// </summary>		
        public awardsSchema CurrentawardsSchema
        {
            get
            {
				return _currentawardsSchema;
            }
            set
            {
                SetProperty(ref _currentawardsSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechawards_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechawards_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentawardsSchema.Subtitle + " " + CurrentawardsSchema.Description);
        }
		

        private ICommand _textToSpeechawards_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechawards_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechawards_DetailStaticControlCommand
        {
            get { return _textToSpeechawards_DetailStaticControlCommand = _textToSpeechawards_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechawards_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Shareawards_DetailStaticControlCommand command.
        /// </summary>
        public  void Shareawards_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentawardsSchema.Subtitle, CurrentawardsSchema.Description);
        }
		

        private ICommand _shareawards_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Shareawards_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Shareawards_DetailStaticControlCommand
        {
            get { return _shareawards_DetailStaticControlCommand = _shareawards_DetailStaticControlCommand ?? new DelegateCommand(Shareawards_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartawards_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartawards_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(Iawards_DetailViewModel), CreateTileInfoawards_DetailStaticControl());
        }
		

        private ICommand _pinToStartawards_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartawards_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartawards_DetailStaticControlCommand
        {
            get { return _pinToStartawards_DetailStaticControlCommand = _pinToStartawards_DetailStaticControlCommand ?? new DelegateCommand(PinToStartawards_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is awardsSchema)) { return; }
                
                CurrentawardsSchema = value as awardsSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the awards_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoawards_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentawardsSchema.Id.ToString(),
                Title = CurrentawardsSchema.Subtitle,
                BackTitle = CurrentawardsSchema.Subtitle,
                BackContent = CurrentawardsSchema.Description,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-3ed85fce-a84f-465c-836d-47785f43766a.png"
            };
            return tileInfo;
        }
    }
}
