// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of TheTeam_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class TheTeam_DetailViewModel : BindableBase, ITheTeam_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="TheTeam_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public TheTeam_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private TheGuysCollectionSchema _currentTheGuysCollectionSchema;

        /// <summary>
        /// CurrentTheGuysCollectionSchema property.
        /// </summary>		
        public TheGuysCollectionSchema CurrentTheGuysCollectionSchema
        {
            get
            {
				return _currentTheGuysCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentTheGuysCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechTheTeam_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentTheGuysCollectionSchema.Title + " " + CurrentTheGuysCollectionSchema.Description);
        }
		

        private ICommand _textToSpeechTheTeam_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechTheTeam_DetailStaticControlCommand
        {
            get { return _textToSpeechTheTeam_DetailStaticControlCommand = _textToSpeechTheTeam_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechTheTeam_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareTheTeam_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentTheGuysCollectionSchema.Title, CurrentTheGuysCollectionSchema.Description);
        }
		

        private ICommand _shareTheTeam_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareTheTeam_DetailStaticControlCommand
        {
            get { return _shareTheTeam_DetailStaticControlCommand = _shareTheTeam_DetailStaticControlCommand ?? new DelegateCommand(ShareTheTeam_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartTheTeam_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(ITheTeam_DetailViewModel), CreateTileInfoTheTeam_DetailStaticControl());
        }
		

        private ICommand _pinToStartTheTeam_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartTheTeam_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartTheTeam_DetailStaticControlCommand
        {
            get { return _pinToStartTheTeam_DetailStaticControlCommand = _pinToStartTheTeam_DetailStaticControlCommand ?? new DelegateCommand(PinToStartTheTeam_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is TheGuysCollectionSchema)) { return; }
                
                CurrentTheGuysCollectionSchema = value as TheGuysCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the TheTeam_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoTheTeam_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentTheGuysCollectionSchema.Id.ToString(),
                Title = CurrentTheGuysCollectionSchema.Title,
                BackTitle = CurrentTheGuysCollectionSchema.Title,
                BackContent = CurrentTheGuysCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentTheGuysCollectionSchema.Image,
                BackBackgroundImagePath = CurrentTheGuysCollectionSchema.Image,
                LogoPath = "Logo-3ed85fce-a84f-465c-836d-47785f43766a.png"
            };
            return tileInfo;
        }
    }
}
