// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of videos_DetailVideos ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class videos_DetailVideosViewModel : BindableBase, Ivideos_DetailVideosViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="videos_DetailVideosViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public videos_DetailVideosViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private YouTubeVideo _currentYouTubeVideo;

        /// <summary>
        /// CurrentYouTubeVideo property.
        /// </summary>		
        public YouTubeVideo CurrentYouTubeVideo
        {
            get
            {
				return _currentYouTubeVideo;
            }
            set
            {
                SetProperty(ref _currentYouTubeVideo, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechvideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechvideos_DetailVideosStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentYouTubeVideo.Title);
        }
		

        private ICommand _textToSpeechvideos_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechvideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechvideos_DetailVideosStaticControlCommand
        {
            get { return _textToSpeechvideos_DetailVideosStaticControlCommand = _textToSpeechvideos_DetailVideosStaticControlCommand ?? new DelegateCommand(TextToSpeechvideos_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharevideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void Sharevideos_DetailVideosStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentYouTubeVideo.Title, " ", CurrentYouTubeVideo.VideoUrl);
        }
		

        private ICommand _sharevideos_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the Sharevideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand Sharevideos_DetailVideosStaticControlCommand
        {
            get { return _sharevideos_DetailVideosStaticControlCommand = _sharevideos_DetailVideosStaticControlCommand ?? new DelegateCommand(Sharevideos_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartvideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void PinToStartvideos_DetailVideosStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(Ivideos_DetailVideosViewModel), CreateTileInfovideos_DetailVideosStaticControl());
        }
		

        private ICommand _pinToStartvideos_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartvideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartvideos_DetailVideosStaticControlCommand
        {
            get { return _pinToStartvideos_DetailVideosStaticControlCommand = _pinToStartvideos_DetailVideosStaticControlCommand ?? new DelegateCommand(PinToStartvideos_DetailVideosStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcevideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public  void GoToSourcevideos_DetailVideosStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(new Uri(CurrentYouTubeVideo.ExternalUrl));
        }
		

        private ICommand _goToSourcevideos_DetailVideosStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcevideos_DetailVideosStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcevideos_DetailVideosStaticControlCommand
        {
            get { return _goToSourcevideos_DetailVideosStaticControlCommand = _goToSourcevideos_DetailVideosStaticControlCommand ?? new DelegateCommand(GoToSourcevideos_DetailVideosStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is YouTubeVideo)) { return; }
                
                CurrentYouTubeVideo = value as YouTubeVideo;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the videos_DetailVideosStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfovideos_DetailVideosStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentYouTubeVideo.VideoId,
                Title = CurrentYouTubeVideo.Title,
                BackTitle = CurrentYouTubeVideo.Title,
                BackContent = string.Empty,
                Count = 0,
                BackgroundImagePath = CurrentYouTubeVideo.VideoImageUrl,
                BackBackgroundImagePath = CurrentYouTubeVideo.VideoImageUrl,
                LogoPath = "Logo-3ed85fce-a84f-465c-836d-47785f43766a.png"
            };
            return tileInfo;
        }
    }
}
