// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// awardsCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class awardsCollection : IawardsCollection 
    {
        private readonly ObservableCollection<awardsSchema> _data = new ObservableCollection<awardsSchema>
		{
          new awardsSchema
            {
                Id= new Guid("37868828-9456-4f53-a01e-96fa9fa5b92d"),
                Title=@"Americas Rugby Championship",
                Subtitle=@"Tournament Trophy",
                Description=@"[Insert the award description here]",
			},
          new awardsSchema
            {
                Id= new Guid("132f82d4-9097-4b42-851a-6e6b3a5e73be"),
                Title=@"Giuseppe Garibaldi Trophy",
                Subtitle=@"Perpetual Trophy",
                Description=@"[Insert the award description here]",
			},
          new awardsSchema
            {
                Id= new Guid("3fcdec0a-37b1-4ef3-b8f7-65542532f281"),
                Title=@"James Bevan Trophy",
                Subtitle=@"Perpetual Trophy",
                Description=@"[Insert the award description here]",
			},
          new awardsSchema
            {
                Id= new Guid("d1438729-d37d-4a8e-ba58-c2ce9ea09d7e"),
                Title=@"Puma Trophy",
                Subtitle=@"Perpetual Trophy",
                Description=@"[Insert the award description here]",
			},
          new awardsSchema
            {
                Id= new Guid("9c281e1a-158f-4610-84fb-242c553f1290"),
                Title=@"The Admiral William Brown Cup",
                Subtitle=@"Perpetual Trophy",
                Description=@"[Insert the award description here]",
			},
          new awardsSchema
            {
                Id= new Guid("6e8e8612-8f5c-4489-88cb-12d749aa99e2"),
                Title=@"Tom Richards Trophy",
                Subtitle=@"Perpetual Trophy",
                Description=@"[Insert the award description here]",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of awardsSchema items.
        /// </summary>
        /// <returns>An observable collection of awardsSchema items.</returns>
        public ObservableCollection<awardsSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of awardsSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of awardsSchema items.</returns>
        public ObservableCollection<awardsSchema> Search(FilterSpecification filter)
        {
            return Filter<awardsSchema>.FilterCollection(filter, _data);
        }
	}
}
