// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// TheGuysCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class TheGuysCollection : ITheGuysCollection 
    {
        private readonly ObservableCollection<TheGuysCollectionSchema> _data = new ObservableCollection<TheGuysCollectionSchema>
		{
          new TheGuysCollectionSchema
            {
                Id= new Guid("984183ed-335f-460b-ac85-f4768484a58d"),
                Title=@"Arnold",
                Image=@"..\Images\Item-316ed668-d3b6-44e9-9c29-5d9564c8931e.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("3951d9f5-ef0e-47ce-bef6-d7ab2128063b"),
                Title=@"Chase",
                Image=@"..\Images\Item-2ed8eb47-4fef-46b6-a5e0-e20d6934c394.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("3cfb710b-1fc8-4181-ab34-13c004a5f4d7"),
                Title=@"Devon",
                Image=@"..\Images\Item-71c526ed-5b38-4650-a57e-666a140f0dcb.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("b2c4732d-a893-4966-8791-53d471e61f3b"),
                Title=@"Jimmy",
                Image=@"..\Images\Item-fdc3fe24-6aa9-47a3-a368-3ad7913b7f70.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("e72304dc-116c-4b70-b5fa-1132272fc8ba"),
                Title=@"Jonh",
                Image=@"..\Images\Item-360ba833-13d6-42ac-86ba-797851d7346e.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("e0e932ff-738a-4a1e-b77f-edcc710fe6a1"),
                Title=@"Joseph",
                Image=@"..\Images\Item-d4ec6aa8-33af-4d36-9209-408a237c67c0.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("d33980fe-9421-4c50-b400-4af95855dfa8"),
                Title=@"Kevin",
                Image=@"..\Images\Item-01b54faa-e1e2-4671-b32d-b161bb3fa210.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("69c82395-f615-4c6e-b06e-1cac27ec33cf"),
                Title=@"Laurent",
                Image=@"..\Images\Item-a0b06e3b-14cb-434a-b4c0-e1dd410fb7eb.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("c1ebb5fe-05ff-491c-b6e6-b59516d0c449"),
                Title=@"Mathew",
                Image=@"..\Images\Item-94e17b45-75ba-4d0f-882b-a367d32cdaf6.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("35db0537-6d9f-4c7a-9855-d5ab51cff127"),
                Title=@"Michael",
                Image=@"..\Images\Item-68288777-c455-483e-a64b-7cf95e979e15.jpg",
                Description=@"[Insert the player description here]",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("15bbb5be-9457-402b-a389-231888189ece"),
                Title=@"Paul",
                Image=@"..\Images\Item-a8b8a1f4-eb6b-40ee-a3ee-e0ac2af7b08f.jpg",
                Description=@"Donec nec eros nec elit ornare rhoncus. Praesent nec adipiscing orci. Etiam adipiscing sapien elit, at feugiat nulla convallis non. Vivamus eget quam non est aliquet imperdiet. Sed auctor, velit eu egestas rhoncus, nisi orci commodo purus, scelerisque porta ligula nulla et est.",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("30ab826f-ebb0-4d83-b751-b0cc08cb0425"),
                Title=@"Sean",
                Image=@"..\Images\Item-ecda6a37-a458-449a-b08f-b408fc8de26b.jpg",
                Description=@"Duis in diam tellus. Donec venenatis tortor tortor, sed congue turpis sagittis sed. Praesent tincidunt quam justo. Aenean urna odio, auctor eu euismod sit amet, mattis a erat. Maecenas porta lorem eu lectus elementum dignissim.",
			},
          new TheGuysCollectionSchema
            {
                Id= new Guid("6f277c3e-d034-4d21-b047-869ac7c641e3"),
                Title=@"Stewart",
                Image=@"..\Images\Item-3e5ba3f3-8899-4d3e-b627-17840e6a91d7.jpg",
                Description=@" Nunc suscipit sapien ante, id congue risus blandit eu. Maecenas auctor cursus vestibulum. Vestibulum bibendum purus a tempus luctus. Curabitur ultrices, velit ut porta varius, diam dolor gravida sem",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of TheGuysCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of TheGuysCollectionSchema items.</returns>
        public ObservableCollection<TheGuysCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of TheGuysCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of TheGuysCollectionSchema items.</returns>
        public ObservableCollection<TheGuysCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<TheGuysCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
