// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   UnityContainer.tt
using Microsoft.Practices.Unity;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.Repositories;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Container : IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<ILiveTileService, LiveTileService>();
			_currentContainer.RegisterType<ILockScreenService, LockScreenService>();
            _currentContainer.RegisterType<IDialogService, DialogService>();
            _currentContainer.RegisterType<IReminderService, ReminderService>();
            _currentContainer.RegisterType<IShareService, ShareService>();
            _currentContainer.RegisterType<ISpeechService, SpeechService>();
            _currentContainer.RegisterType<INavigationService, NavigationService>();
            _currentContainer.RegisterType<IStorageService, StorageService>();

			_currentContainer.RegisterType<IJsonDataSource, JsonDataSource>();
			_currentContainer.RegisterType<IXmlDataSource, XmlDataSource>();
			_currentContainer.RegisterType<IYoutubeDataSource, YoutubeDataSource>();

            _currentContainer.RegisterType<ITheTeam_AlbumViewModel, TheTeam_AlbumViewModel>();
            _currentContainer.RegisterType<Iblog_DetailViewModel, blog_DetailViewModel>();
            _currentContainer.RegisterType<Ivideos_DetailVideosViewModel, videos_DetailVideosViewModel>();
            _currentContainer.RegisterType<Iawards_DetailViewModel, awards_DetailViewModel>();
            _currentContainer.RegisterType<ITheTeam_DetailViewModel, TheTeam_DetailViewModel>();
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<ITheGuysCollection, TheGuysCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IawardsCollection, awardsCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IvideosDataSource, videosDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IblogDataSource, blogDataSource>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<ITheGuysCollection, FakeTheGuysCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IawardsCollection, FakeawardsCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IvideosDataSource, FakevideosDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IblogDataSource, FakeblogDataSource>(new ContainerControlledLifetimeManager());
			
			}	
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
